<?php

namespace App\Services\Employees\Management;

class EmployeeValidationRulesProvider
{
    public function createRules(): array
    {
        return [
            'name' => 'required|min_length[3]|max_length[255]',
            'birth_date' => 'required|valid_date[Y-m-d]',
            'cpf' => 'required|exact_length[11]|regex_match[/^\d{11}$/]|cpf_is_unique',
            'rg' => 'required|min_length[5]|max_length[20]',
            'rg_orgao_emissor' => 'required|min_length[2]|max_length[10]',
            'rg_data_expedicao' => 'required|valid_date[Y-m-d]',
            'estado_civil' => 'required|in_list[solteiro,casado,divorciado,viuvo,uniao_estavel]',
            'nacionalidade' => 'required|min_length[3]|max_length[50]',
            'sexo' => 'required|in_list[masculino,feminino]',
            'cor_raca' => 'required|in_list[branca,preta,parda,amarela,indigena]',
            'grau_instrucao' => 'required|in_list[analfabeto,fundamental_incompleto,fundamental_completo,medio_incompleto,medio_completo,superior_incompleto,superior_completo,pos_graduacao]',
            'logradouro' => 'required|min_length[3]|max_length[255]',
            'numero' => 'required|min_length[1]|max_length[10]',
            'complemento' => 'permit_empty|max_length[100]',
            'bairro' => 'required|min_length[2]|max_length[100]',
            'municipio' => 'required|min_length[2]|max_length[100]',
            'uf' => 'required|exact_length[2]|in_list[AC,AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO]',
            'cep' => 'required|exact_length[8]|regex_match[/^\d{8}$/]',
            'telefone' => 'required|valid_phone_br',
            'email' => 'required|valid_email|max_length[255]|is_unique[employees.email]',
            'ctps_numero' => 'required|min_length[5]|max_length[15]',
            'ctps_serie' => 'required|min_length[3]|max_length[10]',
            'ctps_uf' => 'required|exact_length[2]|in_list[AC,AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO]',
            'ctps_data_emissao' => 'required|valid_date[Y-m-d]',
            'pis_pasep' => 'required|exact_length[11]|regex_match[/^\d{11}$/]|is_unique[employees.pis_pasep]',
            'admission_date' => 'required|valid_date[Y-m-d]',
            'cargo' => 'required|min_length[3]|max_length[100]',
            'salario_base' => 'required|decimal',
            'jornada_trabalho' => 'required|min_length[5]|max_length[50]',
            'tipo_contrato' => 'required|in_list[CLT,temporario,estagio,terceirizado]',
            'setor' => 'required|min_length[2]|max_length[100]',
            'horario_entrada' => 'required|regex_match[/^\d{2}:\d{2}$/]',
            'horario_saida' => 'required|regex_match[/^\d{2}:\d{2}$/]',
            'banco' => 'required|min_length[3]|max_length[50]',
            'agencia' => 'required|min_length[4]|max_length[10]',
            'conta' => 'required|min_length[5]|max_length[20]',
            'deficiencia' => 'permit_empty|in_list[sim,nao]|max_length[100]',
            'demission_date' => 'permit_empty|valid_date[Y-m-d]',
            'role' => 'required|valid_employee_role',
            'work_unit' => 'required',
            'password' => 'required|min_length[8]',
        ];
    }

    public function updateRules(int $id): array
    {
        return [
            'name' => 'required|min_length[3]|max_length[255]',
            'birth_date' => 'required|valid_date[Y-m-d]',
            'cpf' => "required|exact_length[11]|regex_match[/^\\d{11}$/]|cpf_is_unique[{$id}]",
            'rg' => 'required|min_length[5]|max_length[20]',
            'rg_orgao_emissor' => 'required|min_length[2]|max_length[10]',
            'rg_data_expedicao' => 'required|valid_date[Y-m-d]',
            'estado_civil' => 'required|in_list[solteiro,casado,divorciado,viuvo,uniao_estavel]',
            'nacionalidade' => 'required|min_length[3]|max_length[50]',
            'sexo' => 'required|in_list[masculino,feminino]',
            'cor_raca' => 'required|in_list[branca,preta,parda,amarela,indigena]',
            'grau_instrucao' => 'required|in_list[analfabeto,fundamental_incompleto,fundamental_completo,medio_incompleto,medio_completo,superior_incompleto,superior_completo,pos_graduacao]',
            'logradouro' => 'required|min_length[3]|max_length[255]',
            'numero' => 'required|min_length[1]|max_length[10]',
            'complemento' => 'permit_empty|max_length[100]',
            'bairro' => 'required|min_length[2]|max_length[100]',
            'municipio' => 'required|min_length[2]|max_length[100]',
            'uf' => 'required|exact_length[2]|in_list[AC,AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO]',
            'cep' => 'required|exact_length[8]|regex_match[/^\d{8}$/]',
            'telefone' => 'required|valid_phone_br',
            'email' => "required|valid_email|max_length[255]|is_unique[employees.email,id,{$id}]",
            'ctps_numero' => 'required|min_length[5]|max_length[15]',
            'ctps_serie' => 'required|min_length[3]|max_length[10]',
            'ctps_uf' => 'required|exact_length[2]|in_list[AC,AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO]',
            'ctps_data_emissao' => 'required|valid_date[Y-m-d]',
            'pis_pasep' => "required|exact_length[11]|regex_match[/^\\d{11}$/]|is_unique[employees.pis_pasep,id,{$id}]",
            'admission_date' => 'required|valid_date[Y-m-d]',
            'cargo' => 'required|min_length[3]|max_length[100]',
            'salario_base' => 'required|decimal',
            'jornada_trabalho' => 'required|min_length[5]|max_length[50]',
            'tipo_contrato' => 'required|in_list[CLT,temporario,estagio,terceirizado]',
            'setor' => 'required|min_length[2]|max_length[100]',
            'horario_entrada' => 'required|regex_match[/^\d{2}:\d{2}$/]',
            'horario_saida' => 'required|regex_match[/^\d{2}:\d{2}$/]',
            'banco' => 'required|min_length[3]|max_length[50]',
            'agencia' => 'required|min_length[4]|max_length[10]',
            'conta' => 'required|min_length[5]|max_length[20]',
            'deficiencia' => 'permit_empty|in_list[sim,nao]|max_length[100]',
            'demission_date' => 'permit_empty|valid_date[Y-m-d]',
            'role' => 'required|valid_employee_role',
            'work_unit' => 'required',
        ];
    }
}
